### ISSUE TITLE
Losing notifications after alarmdecoder service restarts

### ISSUE THREAD

**Issue by jjslegacy** [nutechsoftware/alarmdecoder-smartthings#12]
Maybe this is expected but thought I would bring it up.

This morning I updated the webapp which then restarted it.  After that I just realized I am not getting status updates in smartthings.  I have to refresh manually to get an update.   

I did go into settings and click save and that seems to work.  I thought there was a process for regrabbing the notifications?  It was like this all day so it isn't a time thing.

Thanks!

**Comment by f34rdotcom** [comment]
This should be fixed in dev now.
