### ISSUE TITLE
Zones do not update (DSC)

### ISSUE THREAD

**Issue by jmaxxz** [nutechsoftware/alarmdecoder-smartthings#13]
Zones do not update open/close status in smartthings.  Alarm decoder web app's virtual keypad shows open zones (`Secure System Before Arming <>` > `Open Zones Scroll to View <>` >`Zone 07 <>`)

**Comment by f34rdotcom** [comment]
Ok just did some testing and I see EXP messages for faults and the ST UI zone tracking on my first zone sensor once assigned zone 1 show zone 1 open/close no problem. Not sure if this was fixed recently or in the updates I did today.
