### ISSUE TITLE
README.md install steps

### ISSUE THREAD

**Issue by f34rdotcom** [nutechsoftware/alarmdecoder-smartthings#2]
Click 'Enable OAuth in Smart App'
Click Publish -> For Me <---- All I see is an "Update" button nothing said publish.

**Comment by f34rdotcom** [comment]
Need a context change to exit "App Settings" and press "Code"

**Comment by endlesscoil** [comment]
Merged in #5 which includes new setup instructions.  Does this still need changing?

**Comment by f34rdotcom** [comment]
@endlesscoil not at this time. I want to improve the glue configuration of keys etc but I have yet to iron out a good solution. I am leaning toward using createAccessToken() and then given the AlarmDecoder API key to the App that can then PUSH the access token and URL to the alarmdecoder and have it save it instead of having to manually enter this into the AlarmDecoder-web -> Notifications -> SmartThings URL/TOKEN field. Currently having to get this inside of the "Simulator" seems to complicated.
