### ISSUE TITLE
Smart things shows armed rather than stay

### ISSUE THREAD

**Issue by jmaxxz** [nutechsoftware/alarmdecoder-smartthings#20]
For DSC panels smart things shows "Armed" when panel is in "Stay".

```
// Stay Arm
!KPM:[01010011000000000D--],008,[000200000000000000000000000000],"Exit Delay In Progress "
// Away Arm
!KPM:[01010001000000000D--],008,[000200000000000000000000000000],"Exit Delay In Progress "
```

**Comment by jmaxxz** [comment]
Ok after looking at the rest api it appears the problem is in the webapp. The following was returned by 
/api/v1/alarmdecoder when panel was stay armed. Note it is not setting the `panel_armed_stay` correctly
```json
{
  "last_message_received": "!KPM:[01010011000000000D--],008,[000200000000000000000000000000],\"Exit Delay      In Progress     \"", 
  "panel_alarming": false, 
  "panel_armed": true, 
  "panel_armed_stay": false, 
  "panel_bypassed": {
    "null": true
  }, 
  "panel_fire_detected": false, 
  "panel_on_battery": false, 
  "panel_panicked": false, 
  "panel_powered": true, 
  "panel_ready": false, 
  "panel_relay_status": [], 
  "panel_type": "DSC", 
  "panel_zones_faulted": []
}
```

**Comment by f34rdotcom** [comment]
I will test this but I believe the issue is deeper in the DSC firmware. It has trouble knowing if it is arming stay or away during the exit delay. I seem to recall that it would jump from arming to "stay" at the very end.

**Comment by jmaxxz** [comment]
@f34rdotcom the problem does not appear to be in the dsc firmware as you can see from the above messages there is 1 bit different in the KPM message 01010011000000000D vs 01010001000000000D the 7th bit from the left would seem to indicate a stay arm.

**Comment by jmaxxz** [comment]
Not to mention the fact that this use to work with a previous version of the alarm decoder stack.

**Comment by f34rdotcom** [comment]
The 7th bit is BYPASS bit.
https://www.alarmdecoder.com/wiki/index.php/Protocol#Bit_field

This is how DSC arms in that it bypasses zones in stay mode. During the "Exit Delay" on DSC the panel message you sent shows bit field #2 is "ARMED AWAY" on both of your messages.

This is what I have seen as well. Here is a test I just did. Note the HOME bit does not change till the end of the arming cycle. Can you please send me the full arming sequence. These messages are the RAW messages from the AD2* firmware. The layers above this in the web app also have some DSC specific logic that may have broken or changed to deal with the differences(quirks) between panels that I have encountered in development. One work around would be to presume it was STAY arming exit delay if the BYPASS bit #7 is set. I am not an expert in DSC panel programming but if this is expected behaviour then this would be an easy quirk to work around.

```
[10010001000000100D0-],001,[000200000000000000000000000000],"System is       Ready to Arm  <>"
[10010001000000100D0-],001,[000200000000000000000000000000],"System is       Ready to Arm  <>"
[10010001000000100D0-],001,[000200000000000000000000000000],"System is       Ready to Arm  <>"

!INF: Sending my code 1234
!Sending.done

!INF: The ARMED AWAY bit #2 is now active.
[01010011000000100D0-],008,[000200000000000000000000000000],"Exit Delay      In Progress     "
[01010011000000100D0-],008,[000200000000000000000000000000],"Exit Delay      In Progress     "
[01010011000000100D0-],008,[000200000000000000000000000000],"Exit Delay      In Progress     "

!INF:...This went on for a while... My exit delay is too long.
[01010011000000100D0-],008,[000200000000000000000000000000],"Exit Delay      In Progress     "

!INF: The ARMED AWAY bit turns off and the STAY bit turns on at the end of the exit dealy.
[00110011000000100D0-],004,[000200000000000000000000000000],"System Armed    In Stay Mode  <>"
[00110011000000100D0-],004,[000200000000000000000000000000],"System Armed    In Stay Mode  <>"
!INF: With DSC specifically the best indicator of how the panel was armed is the LRR message at the end of the arming cycle. 441 is the OPEN/CLOSE contact ID for STAY MODE.
!LRR:040,1,CID_3441,00
[00110011000000100D0-],004,[000200000000000000000000000000],"System Armed    In Stay Mode  <>"
[00110011000000100D0-],004,[000200000000000000000000000000],"System Armed    In Stay Mode  <>"
[00110011000000100D0-],004,[000200000000000000000000000000],"System Armed    In Stay Mode  <>"

```

**Comment by jmaxxz** [comment]
## Stay arm

```
2019-01-10 03:42:11 | !KPM:[01010011000000000D--],008,[000200000000000000000000000000],"Exit Delay In Progress "

2019-01-10 03:42:11 | !KPM:[01010611000000000D--],008,[000200000000000000000000000000],"Exit Delay In Progress "

// After exit delay

2019-01-10 03:44:11 | !KPM:[00110011000000000D--],004,[000200000000000000000000000000],"System Armed In Stay Mode <>"
```


## Away arm

```
2019-01-10 03:39:05 | !KPM:[01010601000000000D--],008,[000200000000000000000000000000],"Exit Delay In Progress "

2019-01-10 03:39:06 | !KPM:[01010001000000000D--],008,[000200000000000000000000000000],"Exit Delay In Progress "

// After exit delay
019-01-10 03:41:05 | !KPM:[01010001000000000D--],005,[000200000000000000000000000000],"System Armed In Away Mode "
```

**Comment by f34rdotcom** [comment]
I noticed you have the "!KPM:" prefix turned on. This is not the default
setting on the AD2* firmware was this your intention to turn this feature
on.
I have not fully tested with this feature turned on using ST. It maybe a
problem. The default config bit value is ff04.

**Comment by jmaxxz** [comment]
I switched it back to default

**Comment by jmaxxz** [comment]
Problem remains...are we any closer to a fix on this?

**Comment by f34rdotcom** [comment]
FYI. The update I am working on allows for changing the device type and inverting the contact if needed. I just did some testing on a 1832 and so far Arm AWAY or STAY it seems to show the correct state after exit delay. It also shows the EXIT delay and the EXIT DELAY virtual contact activates.

**Comment by f34rdotcom** [comment]
Just an FYI. The Flip Flop with DSC switching from ARMED to STAY at the end is still open so this will stay open. I will look again if I have any way of knowing the armed state prior to the end when I get back into firmware stuff this fall but I recall spending many days on that issue and ended up accepting it as a feature at the time. I also added to the ST readme as a current issue.

**Comment by jmaxxz** [comment]
If possible a short term tweak which would significantly improve the situation would be to assume arm stay during the exit delay rather than arm away.

Updated to the latest to try to get alarm decoder hooked backed into smart things. The current situation is an improvement though still not great as smart things switched the house to arm (away) during the exit period for arm (stay). Which results in sirens if i walk past any motion sensor being monitored by smart things rather than DSC.
