### ISSUE TITLE
smart app not discovering device

### ISSUE THREAD

**Issue by t3living** [nutechsoftware/alarmdecoder-smartthings#24]
when trying to install the smartApp I am unable to get my ADWebApp to be discovered. I have them on the same network as hub, the WebApp is operating fine in the browser, but when I try Send UPNP Discovery in the SmartApp simulator no devices are found.  Any suggestions?

**Comment by f34rdotcom** [comment]
Watch the log for the web app /opt/alarmdecoder-webapp/instance/log/info.log when you hit discover. See if any messages show up. I assume you have enabled UPNP Notification in the AlarmDecoder WebApp.
