### ISSUE TITLE
Suggestion: Motion Sensors

### ISSUE THREAD

**Issue by dcmeglio** [nutechsoftware/alarmdecoder-smartthings#25]
It'd be great if there were a way to add motion sensor zones in addition to contact sensors.

**Comment by f34rdotcom** [comment]
I am now sending over RFX messages. I just need to write some code to wrap these into a device handler and add ways to ADD/REMOVE them.

**Comment by f34rdotcom** [comment]
now available in dev branch. you can create RFX ST virtual contacts.
