### ISSUE TITLE
SHM integration issue

### ISSUE THREAD

**Issue by jgrant50** [nutechsoftware/alarmdecoder-smartthings#28]
Is there a way to remove / re-install just the SHM integration portion?  I've been running the setup on a raspberry pi with absolutely no issues for quite some time.  As of a few days ago, if I disarm the system via SHM, the alarm system does not disarm.  Arming via SHM works fine.  Webapp and libraries are both up to date.  Any suggestions?

**Comment by f34rdotcom** [comment]
Can you look at the logs on the graph page to see if any errors or interesting messages show up when you Disarm.

No easy way to force install process again other than remove and add again but it would be possible to add a new button to the SmartApp to trigger any needed tasks.

**Comment by f34rdotcom** [comment]
How ST keeps locks on devices is still an issue and no "-force" option exists in the API to remove a device so in some cases even on the latest in dev it requires manual removal of all devices when doing an upgrade. I have also seen situations where ST keeps "phantom" objects still live even though they are deleted the code still logs results that it is receiving events. Best to remove everyrthing using the AD2 ST app then manual remove all the remained and finally confirm in the log on the graph page after arm/disarm that no code is still somehow running on deleted devices.

I added a few new tools one "rebuild all" to help a little in this process.
