### ISSUE TITLE
Device is often (almost always) "Not Ready"

### ISSUE THREAD

**Issue by dcmeglio** [nutechsoftware/alarmdecoder-smartthings#31]
My alarm decoder almost always reports as Not Ready. I don't know if it's an async timing issue or what. My AD2 Ready device reads "Open" and my AD2 says "Not Ready." This even happens when I arm. It will briefly switch to an "Armed" status but then in a few minutes it's "Not Ready" again.

**Comment by f34rdotcom** [comment]
Hmm. Can you send me some of your "live" logs from the AlarmDecoder webapp.
20 lines of data should be enough to see what is going on. It also has an app log option That would also help. Please send to ad2usb@support.nutech.com reference issue #31 on github.

**Comment by dcmeglio** [comment]
@f34rdotcom Do I need to do this at any particular time (like after arming/disarming or after a contact opens/closes) or can I just grab the most recent 20 lines?

**Comment by f34rdotcom** [comment]
Hmm. I hope that just 20 lines will help but it maybe needed to do this as you see the app report incorrect data. For now I think just seeing 20 lines at any point when the alarm panel should be in a "steady" state is good enough. If zones are opening and closing ready/notready it will cause some confusion.

**Comment by dcmeglio** [comment]
@f34rdotcom email sent with logs

**Comment by dcmeglio** [comment]
I had both enabled. I just disabled the smartthings one. Could that have been the cause? I'll keep you posted on the results 

Dominick Meglio

**Comment by dcmeglio** [comment]
More logs sent to the email you gave me before.

**Comment by dcmeglio** [comment]
@f34rdotcom any progress from the logs I sent?

**Comment by f34rdotcom** [comment]
I did and needed to get back with you on the results. I was having problems
following the changes you made. The logs seem to still indicate that the
old notification is somehow happening.

Can you confirm you have rebooted your Pi and do this tests again. The logs
seemed to only have a few entries so it was hard to synchronize them.

If possible a few minutes of each log is best. I am available to do this
remotely and confirm the bug in your environment using remote access
software and you can contact me at my office.

I am available for support calls

503 443 2000 x703


Best
SM

**Comment by dcmeglio** [comment]
@f34rdotcom sorry I was out of town, should I be doing anything in particular while capturing the logs? Opening/closing zones? arming/disarming? Or should it just just be while idle?

**Comment by dcmeglio** [comment]
@f34rdotcom ???

**Comment by f34rdotcom** [comment]
Sorry I got distracted :) Nothing special needs to be done just as long as you see the ready state change on the APP over and over a few times then the logs should have enough data I can decode the packets manually and figure out what is happening. Even as many as 30 or so lines of raw logs from the AD2* is enough to see this issue.
