### ISSUE TITLE
Any way to detect night mode?

### ISSUE THREAD

**Issue by dcmeglio** [nutechsoftware/alarmdecoder-smartthings#44]
Is there anyway to detect whether or not the alarm was armed in night mode vs. away/stay?

**Comment by f34rdotcom** [comment]
I have seen a patch and will be looking at merging for adding NIGHT and other modes. Stay tuned.

**Comment by automatorCoder** [comment]
I have to kludge it together in my automation system that parses the API URL:

http://alarmdecoder.local:5000/api/v1/alarmdecoder?apikey=YOURS

If panel_armed_stay is true and the message text is ARMED *INSTANT* then the panel is armed night mode.

IMHO, there should be a panel_armed_night flag

`{
  "last_message_received": "[00100001000010003A--],008,[f70600ff1008008c88020000000000],\"ARMED *INSTANT*                 \"", 
  "panel_alarming": false, 
  "panel_armed": false, 
  "panel_armed_stay": true, 
  "panel_battery_trouble": false, 
  "panel_bypassed": {}, 
  "panel_chime": false, 
  "panel_entry_delay_off": true, 
  "panel_exit": false, 
  "panel_fire_detected": false, 
  "panel_panicked": false, 
  "panel_perimeter_only": false, 
  "panel_powered": true, 
  "panel_ready": false, 
  "panel_relay_status": [], 
  "panel_type": "ADEMCO", 
  "panel_zones_faulted": []
}`

**Comment by f34rdotcom** [comment]
NIGHT would be bit3(armed stay) on and bit16(perimeter only) off bit13(instant) on.

**Comment by automatorCoder** [comment]
Thanks. Any chance at getting a token set for this?

panel_armed_night

**Comment by dcmeglio** [comment]
@f34rdotcom is something like this doable?

**Comment by dcmeglio** [comment]
@automatorCoder am I correct you haven't figured out how to do this?

**Comment by f34rdotcom** [comment]
Ok let me go take a few and see. BBIAB.

**Comment by f34rdotcom** [comment]
panel_armed_night = ( panel_entry_delay_off == true && panel_armed_stay == true )

**Comment by dcmeglio** [comment]
Cool! I'm going to see if I can work that into the app so there are switches and events for it just like away/stay

**Comment by dcmeglio** [comment]
Is there an ADEMCO and DSC command I can use to set night mode? trying to build an arm_night()

**Comment by f34rdotcom** [comment]
According to my dsc keypad emulator code its a toggle pressing '*' when armed home mode only I presume.

/* interior arm/disarm fixme need to be dynamic */
// * on home screen when armed
// "Press (*) for   Interior Disarm "
// "Press (*) for   Interior Arm    "

**Comment by dcmeglio** [comment]
any idea for ADEMCO? I Don't have a DSC to test with

**Comment by dcmeglio** [comment]
On my ademco whe I press the night arm the delay_off = false. However perimeter_only = true...

**Comment by f34rdotcom** [comment]
Ok digging. This is complicated :( One of the many differences that causes pain.
I guess in this case if DSC a button could be added to toggle interior as a nice panel specific feature.

- ADEMCO
  - from disarmed state
    - 'CODE+7'
  - from armed state
    - Must disarm first.
- DSC
  - From disarmed state
    - *9+CODE
  - from armed state
    - ** 
    - toggle similar to chime mode. Arms / Disarms interior zones.

**Comment by f34rdotcom** [comment]
- DSC Arming instant
```
[10010001000000100D--],001,[000200000000000000000000000000],"System is       Ready to Arm  <>"
!Sending.done
[00010001000000100D--],01e,[000200000000000000000000000000],"Press (*) for <>Zone Bypass     "
!Sending.done
[00010001000000100D--],01e,[000200000000000000000000000000],"Press (*) for <>Zone Bypass     "
[00010001000000100D--],01f,[000200000000000000000000000000],"Enter Your      Access Code     "
!Sending.done
[00010001000000100D--],01f,[000200000000000000000000000000],"Enter Your      Access Code     "
[00010611000010100D--],009,[000200000000000000000000000000],"Armed with no   Entry Delay     "
[00010011000010100D--],009,[000200000000000000000000000000],"Armed with no   Entry Delay     "
!LRR:040,1,CID_3401,00
!LRR:040,1,CID_3441,00
[00110011000010100D--],016,[000200000000000000000000000000],"System Armed    In Stay Mode  <>"
```
  - Ademco Arming Instant
```
[10000001000000003A--],010,[f70700160010801c08020000800000],"****DISARMED****  READY TO ARM  "
!Sending.done
[00110301000010003A--],010,[f70700040010038c88020000020000],"ARMED *INSTANT* You may exit now"
[00100001000010003A--],010,[f70700040010808c880200002a2059],"ARMED *INSTANT*  ZONE BYPASSED  "
```
  - DSC armed stay toggle interior (MAX or SLEEP MODE) possible feature for GUI.
```
[00110011000010100D--],016,[000200000000000000000000000000],"System Armed    In Stay Mode  <>"
!Sending.done
[00110011000010100D--],038,[000200000000000000000000000000],"Press (*) for   Interior Arm    "
!Sending.done
[00110011000000100D--],00a,[000200000000000000000000000000],"Interior        Been Armed      "
!Sending.done
[00110011000000100D--],038,[000200000000000000000000000000],"Press (*) for   Interior Arm    "
!Sending.done
[00110011000000100D--],00a,[000200000000000000000000000000],"Interior        Been Armed      "
```

**Comment by f34rdotcom** [comment]
> According to my dsc keypad emulator code its a toggle pressing '*' when armed home mode only I presume.
> 
> /* interior arm/disarm fixme need to be dynamic _/ // * on home screen when armed // "Press (_) for Interior Disarm "
> // "Press (*) for Interior Arm "

This was incorrect and referred to Night mode.

For ademco Night-Stay mode is CODE+33
For DSC Night-Stay is *1 and can only be turned on when the system is armed stay.

I made updates to the prior post to reflect this as well.

**Comment by dcmeglio** [comment]
Interesting. Then I guess for ademco my suspicion was correct that it will be stay+perimeter only? Looks like angry delay is enabled in night stay. I can’t find a good dsc manual to know what it does...

**Comment by dcmeglio** [comment]
@automatorCoder I'm not yet ready to submit this to be merged since I only have Hubitat. Any chance you have SmartThings? If so and you're already using the dev branch here, https://github.com/dcmeglio/alarmdecoder-smartthings/tree/dev has my first attempt at adding night mode support. It seems to be working for me.
