### ISSUE TITLE
Re-Integrating My AD2Pi with SmartThings

### ISSUE THREAD

**Issue by j3tang** [nutechsoftware/alarmdecoder-smartthings#51]
I have had my AD2Pi network appliance working with my Vista20p setup since mid-2018 or so and it has been working without much complaint. It was integrated with SmartThings, although it was an arduous process ... mostly because I'm really need that techy.

However, between me messing around with the new SmartThings app and getting my wife (a new member to the hub) added and her account being used on and off with the ST classics app and the new app, I've had to start from scratch ... I've removed all integrated devices and re-added them all back into the Classic app. The only thing that I am still having issues with is my AlarmDecoder setup.

I've re-added all the contacts/sensors back into SmartThings, but for whatever reason, none of them receive any updates (i.e., I open the front door, I walk by motion sensors, etc. ... none of that is recognized in the ST app). These are all recognized on my panel and everything there functions as normal, it just seems like there is a missing link between it and ST.

I've gone through the process of deleting all the devices from the ST classics app, then going to the IDE to perform updates from the repo for the device handlers, etc. and re-installing from the ST classics app again, but still no change. In case anyone asks, yes i did go into the WebApp to obtain the key to input into the classics app.

**Comment by j3tang** [comment]
I have since re-imaged the Pi with latest. Setup the webapp, reinstalled all the items in the IDE and integrated in smartthings classic app.

Still having the same exact issue I was having in previous post.
The webapp seems to run fine, when I check the logs it sees the zones (contacts or motion sensors) faulting as I move through the house to test them. The webapp sees all the faulting of the zones live as I walk through the home too.  There's just absolutely no updating in the smartthings app.

The app has all my contacts and sensors devices, they all just say "close". Clicking into them and checking their recent activity is blank.
As for the actual alarm decoder device, the only recent history item in it is the moment the device was created. If I recall correctly, that should show you all the faults and changes occurring across all the zones.

**Comment by f34rdotcom** [comment]
Please see the new AlarmDecoder-STSDK project the ST Classic app and dev environment is no longer active.
