### ISSUE TITLE
latest code - alarmdecoder device updates but not the zone tracker sensors unless I refresh

### ISSUE THREAD

**Issue by jjslegacy** [nutechsoftware/alarmdecoder-smartthings#9]
trying out the latest code release.  I believe I have everything updated and had to redo all devices.

When I open a door I instantly see the red circle with the faulted zone in the alarmdecoder device.  The matching device does not change to "open" though.

If I click refresh in the alarmdecoder device then the zone tracker sensor udpates and shows open.

Ideas?

**Comment by jjslegacy** [comment]
Looking more into it -  after the refresh if I close the door the status changes instantly so that seems to work

**Comment by jjslegacy** [comment]
I think the problem is in here:
private def update_zone_switches(zone, faulted) {


If I convert zones to an integer it works

 if (zone.toInteger() == settings."zonetracker${i}zone")

**Comment by f34rdotcom** [comment]
Please review your log on smartthings graph page to see if you had exceptions. I was able to figure out the zone tracker not updating bug and to make it more like the original json parser I now convert the zone to an int() d0610e761d577d3da7cd37cf9fb8e010e54ba9f7 The other issue with it not clearing quickly is odd if you got the update that it was open fast. That is why I suspect an exception occurred only on restore. Let me know if you see more issues and I will re open the ticket.
